# please note these are short paths based on the docker container set with -v flags

# where data is stored
data_location = "/data/"

# where model binaries should be stored
model_location = "/modelbinaries/"

# model params is where any hyperparameters are stored for each model
params_location = "/modelparams/"

# where to store processed data after creating features
processed_data_location = "/processeddata/"

# stream prefixes
# all models will have the prefix of the full stream name
# ie. z5_cryptoxxx will store the model as z5_cryptoxxx.pkl and data as z5_cryptoxxx.csv or json
stream_prefixes = ["c2", "c5", "fathom"]

# email for prizes, use this if you want your money
email = "freemoney@free.com"

# max moving average lags, controls how many features are used to create a moving average to limit computation time
max_ma_lags = 24

# how many lags to limit on % changes 
max_diff_lags = 5

# what forecast horizons to do, 1 lag is 15 minutes so 4 is an hour
forecast_horizons = [3, 4]


# used for making sure the target is handled correctly when the values are not difference, use the stream prefix to handle
# that way the target can then be defined as the diff and not the raw value, and then prediction handled accordingly
stream_raw_values = ["electricity"]

# update schedule, use these as flags either daily, weekly or monthly alternative use a separate process and let jenkins cron handle it
# if someone else wants to add code to do a different schedule feel free or just alter the

# based on cront
model_schedule = "weekly"

stream_schedule = {hour="*",minute=1}